"""empty message

Revision ID: 2574fa76678d
Revises: 115ec8f90dd4
Create Date: 2019-05-01 14:14:54.539814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2574fa76678d'
down_revision = '115ec8f90dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_update')
    # ### end Alembic commands ###
