"""empty message

Revision ID: 808335a393bc
Revises: 2574fa76678d
Create Date: 2019-05-02 22:34:10.021892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808335a393bc'
down_revision = '2574fa76678d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('hash', sa.String(length=80), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
